version: '3.7'

volumes:
  spark-pg-data:

services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5433:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - spark-pg-data:/var/lib/postgresql/data